name: Build GSI

on:
  workflow_dispatch:


jobs:
  build-gsi:
    runs-on: ubuntu-22.04
    steps:
    - name: setup git config
      run: |
        git config --global user.email "androidbuild@localhost"
        git config --global user.name "androidbuild"
        
    - name: checkout basic repo
      uses: actions/checkout@v4
    - name: clone rom manifest
      run: |
          mkdir rising
          sudo apt update && sudo apt install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-gtk3-dev libxml2 libxml2-utils lzop pngcrush repo rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
          repo init -u https://github.com/RisingTechOSS/android -b fourteen --git-lfs
      
    - name: perform full sources sync (with auto retry)
      uses: nick-fields/retry@v3
      with:
        command: |
            cd rising
            repo sync -c -j4 --force-sync --no-clone-bundle --no-tags
        max_attempts: 10
        retry_on: error
        timeout_minutes: 40

    - name: sync the device trees with git clone
      run: |
       cd rising
       git clone --depth=1 -b main https://github.com/Hasajapathirana/android_vendor_samsung_universal2100-common vendor/samsung/universal2100-common
       git clone --depth=1 -b main https://github.com/Hasajapathirana/android_vendor_samsung_p3s vendor/samsung/p3s
       git clone --depth=1 -b lineage-21 https://github.com/Exynos2100-common/android_vendor_samsung_o1s vendor/samsung/o1s 
       git clone --depth=1 -b lineage-21 https://github.com/Exynos2100-common/android_vendor_samsung_r9s vendor/samsung/r9s
       git clone --depth=1 -b lineage-21-bsp https://github.com/Exynos2100-common/android_device_samsung_universal2100-common device/samsung/universal2100-common
       git clone --depth=1 -b lineage-21 https://github.com/Hasajapathirana/android_device_samsung_p3s device/samsung/p3s
       git clone --depth=1 -b lineage-21 https://github.com/Exynos2100-common/android_device_samsung_o1s device/samsung/o1s
       git clone --depth=1 -b lineage-21 https://github.com/Exynos2100-common/android_device_samsung_r9s device/samsung/r9s
       git clone --depth=1 -b 14 https://github.com/Exynos2100-common/android_hardware_samsung_slsi-linaro_graphics hardware/samsung_slsi-linaro/graphics
       git clone --depth=1 -b 14 https://github.com/Exynos2100-common/android_hardware_samsung_slsi-linaro_exynos hardware/samsung_slsi-linaro/exynos
       git clone --depth=1 -b lineage-21 https://github.com/Exynos2100-common/android_hardware_samsung_slsi-linaro_config hardware/samsung_slsi-linaro/config
       git clone --depth=1 -b 14 https://github.com/Exynos2100-common/android_hardware_samsung_slsi-linaro_exynos5 hardware/samsung_slsi-linaro/exynos5
       git clone --depth=1 -b lineage-21 https://github.com/Exynos2100-common/android_hardware_samsung_slsi-linaro_openmax hardware/samsung_slsi-linaro/openmax
       git clone --depth=1 -b FWK2 https://github.com/Exynos2100-common/android_kernel_samsung_universal2100 kernel/samsung/universal2100
       git clone --depth=1 -b lineage-21 https://github.com/Exynos2100-common/android_hardware_samsung-ext_interfaces hardware/samsung-ext/interfaces
       git clone --depth=1 -b lineage-21 https://github.com/Exynos2100-common/android_hardware_samsung_slsi-linaro_interfaces hardware/samsung_slsi-linaro/interfaces
       git clone --depth=1 -b lineage-21 https://github.com/Exynos2100-common/vendor_firmware vendor/firmware
       git clone --depth=1 -b 14 https://github.com/Exynos2100-common/android_hardware_samsung hardware/samsung
       git clone --depth=1 -b lineage-21 https://github.com/Exynos2100-common/android_device_samsung_slsi_sepolicy device/samsung_slsi/sepolicy
  
    - name: Building RisingOS
      run: |
         cd rising
         . build/envsetup.sh
         riseup p3s userdebug
         rise b
         
      working-directory: src/out/target/product/p3s
    - name: upload to github
      run: |
          git init
          git remote add origin "https://github.com/Hasajapathirana/treble.git"
          gh repo set-default "Hasajapathirana/treble"
          gh release create -d -n "" -t "RisingOS-5.2-p3s"
          cd rising
          ls
          cd out
          cd target
          cd product
          cd p3s
          gh release upload *p3s*.zip
          gh release upload recovery.img
          rm -rf .git/
        
        
